jakarta.persistence.jdbc.driver=org.postgresql.Driver
jakarta.persistence.jdbc.url=jdbc:postgresql://localhost:5432/users
jakarta.persistence.jdbc.user=postgres
jakarta.persistence.jdbc.password=postgres

hibernate.hbm2ddl.auto=create
#hibernate.hbm2ddl.auto=update
hibernate.show_sql=true
hibernate.format_sql=true
